[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Name = "Hello"
Version = "0.1.0"
Type = "Executable"
Authors = ["Rux Contributors <info@rux-lang.dev>"]
Description = "Simple console application"

[Dependencies]
Io = { Namespace = "Rux", Version = "*" }
