[Manifest]
Version = 1
MinRux = "0.4.0"

[Package]
Name = "Circle"
Version = "0.1.0"
Type = "Executable"
Authors = ["Rux Contributors <info@rux-lang.dev>"]
Description = "Calculates the circumference and area of a circle"

[Dependencies]
Format = { Namespace = "Rux", Version = "*" }
Io = { Namespace = "Rux", Version = "*" }
Math = { Namespace = "Rux", Version = "*" }

[Build]
Output = "Bin"
